name: CI - FastAPI Cookbook

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sort imports
        run: |
          pip install isort
          isort --profile black .

      - name: Format code with Black
        run: |
          pip install black
          black .

      - name: Run linters (checks)
        run: |
          pip install flake8
          isort --check-only --profile black .
          black --check .
          flake8 .

      - name: Run tests
        run: |
          pip install pytest pytest-cov httpx
          pytest --cov=app --maxfail=1 --disable-warnings -q

