name: CI - FastAPI Cookbook

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linters
        run: |
          black .
          isort --check-only .
          flake8 .

      - name: Run tests
        run: pytest --cov=app --maxfail=1 --disable-warnings -q
